name: Terraform Delete IAM Resources Workflow

on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Retrieve Terraform Outputs
        id: get_outputs
        run: |
          echo "::set-output name=iam_user_names::$(terraform output -json iam_user_names)"
          echo "::set-output name=iam_group_name::$(terraform output -json iam_group_name)"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="iam_user_names=${{ steps.get_outputs.outputs.iam_user_names }}" -var="iam_group_name=${{ steps.get_outputs.outputs.iam_group_name }}"
