name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Change this to match your desired Terraform version

    - name: Terraform Init
      run: terraform init

  plan_iam_user:
    needs: init
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Terraform Plan IAM User
      run: terraform plan -out=tfplan_iam_user
      working-directory: modules/iam_user

  plan_iam_group:
    needs: init
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Terraform Plan IAM Group
      run: terraform plan -out=tfplan_iam_group
      working-directory: modules/iam_group

  apply_iam_user:
    needs: plan_iam_user
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Terraform Apply IAM User
      run: terraform apply -auto-approve tfplan_iam_user
      working-directory: modules/iam_user

  apply_iam_group:
    needs: plan_iam_group
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Terraform Apply IAM Group
      run: terraform apply -auto-approve tfplan_iam_group
      working-directory: modules/iam_group
